title: "fREW Schmidt's Clog (Coffee Blog)"
author:
  name: "Arthur Axel fREW Schmidt"
  twitter: frioux
indexes:
  tag: 'tags'
baseURL: 'https://frioux.github.io/clog'
paginate: 50
q:
  post-facets:
    - roast_level
    - total_roast
    - first_crack
    - rating
    - start_weight
    - end_weight
