title: "fREW Schmidt's Clog (Coffee Blog)"
author:
  name: "Arthur Axel fREW Schmidt"
  twitter: frioux
indexes:
  tag: 'tags'
baseurl: 'https://frioux.github.io/clog'
canonifyurls: false
paginate: 50
